# --------------------------------------------------------------------------------------------------
# Instructions for new profiles
# --------------------------------------------------------------------------------------------------

# 1. Run the `cli project init PROJECT_NAME` command.
# 2. Copy and append the following template to this file.

# <PROJECT_NAME>:
#   target: dev
#   outputs:
#     dev:
#       type: clickhouse
#       threads: 1
#       host: "{{ env_var('<PROJECT_NAME>_DESTINATION_CLICKHOUSE_HOST') }}"
#       port: "{{ env_var('<PROJECT_NAME>_DESTINATION_CLICKHOUSE_PORT')|as_number }}"
#       user: "{{ env_var('<PROJECT_NAME>_DESTINATION_CLICKHOUSE_USERNAME') }}"
#       password: "{{ env_var('<PROJECT_NAME>_DESTINATION_CLICKHOUSE_PASSWORD') }}"
#       schema: "{{ env_var('<PROJECT_NAME>_DESTINATION_CLICKHOUSE_DATABASE') }}"
#       driver: "{{ env_var('<PROJECT_NAME>_DESTINATION_CLICKHOUSE_DRIVER') }}"
#       secure: "{{ (env_var('<PROJECT_NAME>_DESTINATION_CLICKHOUSE_SECURE') == 'true')|as_bool }}"
#       use_lw_deletes: true

# 3. Replace `<PROJECT_NAME>` with the project name. Must be lowercase except for env variables that must be uppercase.
# 4. Run the `cli project refresh PROJECT_NAME` command.

tutorial:
  target: dev
  outputs:
    dev:
      type: clickhouse
      threads: 1
      host: "{{ env_var('TUTORIAL_DESTINATION_CLICKHOUSE_HOST') }}"
      port: "{{ env_var('TUTORIAL_DESTINATION_CLICKHOUSE_PORT')|as_number }}"
      user: "{{ env_var('TUTORIAL_DESTINATION_CLICKHOUSE_USERNAME') }}"
      password: "{{ env_var('TUTORIAL_DESTINATION_CLICKHOUSE_PASSWORD') }}"
      schema: "{{ env_var('TUTORIAL_DESTINATION_CLICKHOUSE_DATABASE') }}"
      driver: "{{ env_var('TUTORIAL_DESTINATION_CLICKHOUSE_DRIVER') }}"
      secure: "{{ (env_var('TUTORIAL_DESTINATION_CLICKHOUSE_SECURE') == 'true')|as_bool }}"
      use_lw_deletes: true

main:
  target: dev
  outputs:
    dev:
      type: clickhouse
      threads: 1
      host: "{{ env_var('MAIN_DESTINATION_CLICKHOUSE_HOST') }}"
      port: "{{ env_var('MAIN_DESTINATION_CLICKHOUSE_PORT')|as_number }}"
      user: "{{ env_var('MAIN_DESTINATION_CLICKHOUSE_USERNAME') }}"
      password: "{{ env_var('MAIN_DESTINATION_CLICKHOUSE_PASSWORD') }}"
      schema: "{{ env_var('MAIN_DESTINATION_CLICKHOUSE_DATABASE') }}"
      driver: "{{ env_var('MAIN_DESTINATION_CLICKHOUSE_DRIVER') }}"
      secure: "{{ (env_var('MAIN_DESTINATION_CLICKHOUSE_SECURE') == 'true')|as_bool }}"
      use_lw_deletes: true
