version: "3.8"

volumes:
  prefect_postgres_data:

services:
  prefect-postgres:
    image: postgres:16.1-alpine3.19
    env_file:
      - ./.env_files/prefect-postgres.env
    ports:
      - ${DW_PREFECT_POSTGRES_PORT:-5432}:5432
    volumes:
      - ./docker/dw-prefect/prefect-postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - prefect_postgres_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure

  prefect-server:
    build:
      context: ./docker/dw-prefect/prefect-base
    command: prefect server start
    env_file:
      - ./.env_files/prefect-server.env
    ports:
      - ${DW_PREFECT_SERVER_PORT:-4200}:4200
    volumes:
      - ./.prefect:/home/analyst/.prefect:rw
    healthcheck:
      test: curl --fail http://0.0.0.0:4200/api/health || exit 1
      interval: 1s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      prefect-postgres:
        condition: service_healthy

  prefect-worker:
    build:
      context: ./docker/dw-prefect/prefect-base
    command: prefect worker start --name process-worker --pool process_pool --type process --limit 1
    env_file:
      - ./.env_files/prefect-worker.env
      - ./.env_files/database.env
    extra_hosts:
      - host.docker.internal:host-gateway # Used for connection to ClickHouse
    volumes:
      - ./.dbt:/home/analyst/.dbt:rw
      - ./.prefect:/home/analyst/.prefect:rw
      - ./package:/home/analyst/package:rw
      - ./projects:/home/analyst/projects:rw
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      prefect-server:
        condition: service_healthy

  cli:
    build:
      context: ./docker/dw-prefect/prefect-base
    command: /bin/bash
    env_file:
      - ./.env_files/cli.env
      - ./.env_files/database.env
    working_dir: /home/analyst/projects
    extra_hosts:
      - host.docker.internal:host-gateway # Used for connection to ClickHouse
    volumes:
      - .:/home/analyst:rw
      - ${SSH_AUTH_SOCK}:/ssh-agent:ro
    stdin_open: true
    tty: true
    depends_on:
      prefect-server:
        condition: service_healthy
      # TODO Uncomment after adding healthcheck to prefect-worker
      # prefect-worker:
      #   condition: service_healthy

  jupyter:
    build:
      context: ./docker/dw-prefect/jupyter
    env_file:
      - ./.env_files/jupyter.env
      - ./.env_files/database.env
    extra_hosts:
      - host.docker.internal:host-gateway # Used for connection to ClickHouse
    ports:
      - ${DW_JUPYTER_PORT:-8888}:8888
    volumes:
      - ./.dbt:/home/analyst/.dbt:rw
      - ./.ipython/profile_default/startup:/home/analyst/.ipython/profile_default/startup:rw
      - ./.jupyter/jupyter_server_config.py:/home/analyst/.jupyter/jupyter_server_config.py:rw
      - ./.prefect:/home/analyst/.prefect:rw
      - ./package:/home/analyst/package:rw
      - ./projects:/home/analyst/projects:rw
      - ./docker/dw-prefect/jupyter/usr/local/bin/start-notebook.d:/usr/local/bin/start-notebook.d:ro
    user: 0:0

  api:
    build:
      context: ./docker/dw-prefect/api
    command: uvicorn main:app --app-dir /home/analyst/projects/tutorial/api --host 0.0.0.0 --port 80 --reload
    env_file:
      - ./.env_files/api.env
      - ./.env_files/database.env
    working_dir: /home/analyst/projects/tutorial/api
    extra_hosts:
      - host.docker.internal:host-gateway # Used for connection to ClickHouse
    ports:
      - ${DW_API_PORT:-8080}:80
    volumes:
      - .:/home/analyst:rw
