name: peerdb

services:
  catalog:
    extends:
      file: ../../vendor/peerdb/docker-compose.yml
      service: catalog

  temporal:
    extends:
      file: ../../vendor/peerdb/docker-compose.yml
      service: temporal

  temporal-admin-tools:
    extends:
      file: ../../vendor/peerdb/docker-compose.yml
      service: temporal-admin-tools

  temporal-ui:
    extends:
      file: ../../vendor/peerdb/docker-compose.yml
      service: temporal-ui

  flow-api:
    extends:
      file: ../../vendor/peerdb/docker-compose.yml
      service: flow-api

  flow-snapshot-worker:
    extends:
      file: ../../vendor/peerdb/docker-compose.yml
      service: flow-snapshot-worker
    extra_hosts:
      - host.docker.internal:host-gateway

  flow-worker:
    extends:
      file: ../../vendor/peerdb/docker-compose.yml
      service: flow-worker

  peerdb:
    extends:
      file: ../../vendor/peerdb/docker-compose.yml
      service: peerdb

  peerdb-ui:
    extends:
      file: ../../vendor/peerdb/docker-compose.yml
      service: peerdb-ui

  minio:
    extends:
      file: ../../vendor/peerdb/docker-compose.yml
      service: minio

volumes:
  pgdata:
  minio-data:

networks:
  default:
    name: dw
