name: dw-monitor

services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    env_file:
      - ./cadvisor.env
    ports:
      - ${DW_CADVISOR_PORT}:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.1
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=warn
    env_file:
      - ./prometheus.env
    ports:
      - ${DW_PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus:rw
    depends_on:
      - cadvisor

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:10.4.14
    env_file:
      - ./grafana.env
    ports:
      - ${DW_GRAFANA_PORT}:3000
    volumes:
      - ./grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana/provisioning/providers.yml:/etc/grafana/provisioning/dashboards/providers.yml:ro
      - ./grafana/dashboards:/etc/dashboards:ro
      - ./grafana/dashboards/home.json:/usr/share/grafana/public/dashboards/home.json:ro
      - grafana-data:/var/lib/grafana:rw
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:

networks:
  default:
    name: dw
