name: {{ project_name }}
version: 1.0.0
config-version: 2

profile: {{ project_name }}

model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]
clean-targets: [logs, target, dbt_packages]

models:
  {{ project_name }}:
    +materialized: view

    dbt:
      dbt_artifacts:
        +schema: dbt_artifacts

on-run-end:
  - "{{ upload_run_results(results) }}"

vars:
  dbt_audit_column_names: [_dbt_build_time, _dbt_build_type, _dbt_build_num, _dbt_last_full_refresh]
