name: {{ project_name }}
version: 1.0.0
config-version: 2

profile: {{ project_name }}

model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]
clean-targets: [logs, target, dbt_packages]

models:
  dbt_audit:
    +schema: dbt_audit

  {{ project_name }}:
    +materialized: view

vars:
  dbt_audit_column_names: [dbt_run_id]
