repos:
  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]
        stages: [pre-commit]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--settings-path, pyproject.toml]
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        alias: ruff-lint
        args: [--config, pyproject.toml]
        stages: [manual]
      - id: ruff-format
        alias: ruff
        args: [--config, pyproject.toml]
        stages: [pre-commit]
