version: 2

models:
- name: dbt_run
  columns:
  - name: id
    data_type: UInt64
  - name: invocation_id
    data_type: UUID
  - name: node_id
    data_type: String
  - name: thread_id
    data_type: String
  - name: resource_type
    data_type: String
  - name: schema
    data_type: String
  - name: name
    data_type: String
  - name: alias
    data_type: String
  - name: materialization
    data_type: String
  - name: run_type
    data_type: String
  - name: run_start_time
    data_type: DateTime64(6)
  - name: compile_start_time
    data_type: Nullable(DateTime64(6))
  - name: compile_duration
    data_type: Nullable(UInt64)
    description: Duration in milliseconds.
  - name: execute_start_time
    data_type: Nullable(DateTime64(6))
  - name: execute_duration
    data_type: Nullable(UInt64)
    description: Duration in milliseconds.
  - name: status
    data_type: String
  - name: message
    data_type: String
  - name: rows_affected
    data_type: Nullable(UInt64)
  - name: adapter_response
    data_type: String
